version: '3.8'

services:
  app-with-database:
    container_name: 'appWithDatabaseContainer'
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=myuser
      - PASSWORD=mypassword
      - DB_NAME=mydatabase
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: 'databaseContainer'
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
